name: CI Pipeline

on:
  push:
    branches: [ "main", "dev", "feature/app" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean compile

    - name: Run Unit Tests
      run: mvn -Dtest=!SeleniumTest test

    - name: Package JAR
      run: mvn -DskipTests package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: devops-app/target/*.jar
        retention-days: 5
